Disable embedded server per default
nolequen/vertx-prometheus-metrics pull request #21
Opened 2018-03-28 12:11 UTC by marcust

As per reasoning in #20

2018-04-02 12:35 UTC, nolequen commented
@marcust thanks for your PR.
Could you please fix and squash your commits?

2018-04-02 12:36 UTC, nolequen requested changes

2018-04-02 12:36 UTC, nolequen commented on src/main/java/io/vertx/ext/prometheus/VertxPrometheusOptions.java
> +   * Alias for {@code enableEmbeededServer}
Please, don't create an alias. Use the existing method or replace it with the new one.

2018-04-10 07:12 UTC, marcust commented
Done

2018-04-10 11:25 UTC, merged

2018-04-10 11:25 UTC, nolequen commented
@marcust thank you!